version: '3'

services:
  fil_rouge1:
    build: ./docker_fil_rouge
    ports:
      - "8000:8000"
    network_mode: host

  fil_rouge2:
    build: ./docker_fil_rouge
    ports:
      - "8000:8000"
    network_mode: host

  fil_rouge3:
    build: ./docker_fil_rouge
    ports:
      - "8000:8000"
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fil_rouge1
      - fil_rouge2
      - fil_rouge3
    volumes:
      - ./nginx/filrouge.conf:/etc/nginx/conf.d/defaut.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    environment: 
      - SERVER_NAME=52.73.208.172
    restart: always
    network_mode: host
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"