version: '3'

services:
  fil_rouge:
    build: ./docker_fil_rouge
    ports:
      - "8000:8000"
    network_mode: host
  
  nginx:
    build: ./nginx
    container_name: nginx
    environment: 
        - SERVER_NAME=52.73.208.172
    restart: always
    network_mode: host