version: '3'

services: 
    Fil_rouge:
        build: ./docker_fil_rouge
        container_name: Fil_rouge
        network_mode: host
        restart: always
        environment: 
            - AWS_PROFILE=csloginstudent
            - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
            - AWS_CONFIG_FILE=/aws/config
        ports:
            - "4995-4999:8000"
    nginx:
        build: ./nginx
        container_name: nginx
        ports :
            - "80:80"
            - "443:443"
        restart: always
        network_mode: host
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot  
        depends_on:
            - Fil_rouge
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${​​!}​​; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${​​!}​​; done;'
        

